# Generated by Django 5.2 on 2025-05-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_feed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feeds_source',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Источник ленты'),
        ),
        migrations.AddField(
            model_name='feed',
            name='send_feed',
            field=models.IntegerField(default=0, verbose_name='Отправить ленту'),
        ),
    ]
