# Generated by Django 5.2 on 2025-05-29 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_alter_feedcomment_feed_alter_feedcomment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlike',
            name='id',
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
