# Generated by Django 5.2 on 2025-05-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_remove_feedlike_id_alter_feedlike_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcommentlike',
            name='feed_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='feeds.feedcomment', verbose_name='Комментарии'),
        ),
    ]
