# Generated by Django 5.2 on 2025-05-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_alter_feedcommentlike_feed_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': '2. Лента', 'verbose_name_plural': '2. Ленты'},
        ),
        migrations.AlterModelOptions(
            name='feedcategory',
            options={'verbose_name': '1. Категория', 'verbose_name_plural': '1. Категории'},
        ),
        migrations.AlterModelOptions(
            name='feedcommentlike',
            options={'verbose_name': 'Комментарии Лайк', 'verbose_name_plural': ' Комментарии Лайки'},
        ),
    ]
