# Generated by Django 5.2 on 2025-05-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_alter_feed_options_alter_feedcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feed',
            options={'verbose_name': '2. Feed', 'verbose_name_plural': '2. Feeds'},
        ),
        migrations.AlterModelOptions(
            name='feedcategory',
            options={'verbose_name': '1. Category', 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='feedcomment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='feedcommentlike',
            options={'verbose_name': 'Comment Like', 'verbose_name_plural': 'Comment Likes'},
        ),
        migrations.AlterModelOptions(
            name='feedlike',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterField(
            model_name='feed',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='feeds.feedcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='feeds_source',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Feed Source'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='send_feed',
            field=models.IntegerField(default=0, verbose_name='Send Feed'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='type',
            field=models.CharField(choices=[('reels', 'Reels'), ('advertisement', 'Advertisement')], default='reels', max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video File'),
        ),
        migrations.AlterField(
            model_name='feedcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feeds.feed', verbose_name='Feed'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='feedcommentlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedcommentlike',
            name='feed_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to='feeds.feedcomment', verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='feedcommentlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_comment_likes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.feed', verbose_name='Feed'),
        ),
        migrations.AlterField(
            model_name='feedlike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
