# Generated by Django 5.2 on 2025-05-29 16:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1. Category', 'verbose_name_plural': '1. Categories'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'verbose_name': '2. Product', 'verbose_name_plural': '2. Products'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '3. Order', 'verbose_name_plural': '3. Orders'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='market',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='market',
            name='image',
            field=models.ImageField(upload_to='market/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='market',
            name='price_dollor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)'),
        ),
        migrations.AlterField(
            model_name='market',
            name='price_fiptp',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (FIPTP)'),
        ),
        migrations.AlterField(
            model_name='market',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15, null=True, verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_shipping',
            field=models.BooleanField(default=False, verbose_name='Shipping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.market', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sizes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=15, verbose_name='Sizes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip_code',
            field=models.CharField(max_length=20, verbose_name='Postal Code'),
        ),
    ]
