# Generated by Django 5.2 on 2025-05-12 06:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ddda8cc8-8abc-4e69-9877-a8ba2593a74c'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
