# Generated by Django 5.2 on 2025-05-12 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_image_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3cd2e7dc-0ef0-4a0e-b332-f18798f6a56f'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
