# Generated by Django 5.2 on 2025-05-01 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_tg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earn_per_tab', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Заработок за вкладку')),
                ('coin_level', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Уровень монеты')),
                ('profit_per_hour', models.FloatField(blank=True, default=0, null=True, verbose_name='Прибыль в час')),
                ('coin', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True, verbose_name='Монета')),
                ('profile_type', models.CharField(choices=[('Rookie Voyeur', 'Rookie Voyeur  Voyeur'), ('Late-Night Scroller', 'Late-Night Scroller'), ('Naughty Subscriber', 'Naughty Subscriber'), ('Private Teaser', 'Private Teaser'), ('Erotic Enthusiast', 'Erotic Enthusiast'), ('XXX VIP', 'XXX VIP'), ('Hardcore Legend', 'Hardcore Legend'), ('Kink Master', 'Kink Master'), ('Adult Insider', 'Adult Insider'), ('Exclusive Pleasure-Seeker', 'Exclusive Pleasure-Seeker'), ('FIPT Legend', 'FIPT Legend')], default='Rookie Voyeur', max_length=50, verbose_name='Тип профиля')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='Изображение')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
