# Generated by Django 5.2 on 2025-05-12 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_avatar_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6145d2f2-f512-4d8d-a10f-5d2848696696'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
