# Generated by Django 5.2 on 2025-05-29 12:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userprofile_uuid_referals'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferalsPoints',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID')),
                ('points', models.DecimalField(decimal_places=1, default=0, max_digits=10, verbose_name='Баллы')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баллы рефералов',
                'verbose_name_plural': 'Баллы рефералов',
            },
        ),
        migrations.AddField(
            model_name='channelsuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7300cb5f-c716-4ef5-8131-d4e5d822158d'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
