# Generated by Django 5.2 on 2025-05-29 14:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_referalspoints_channelsuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('13c0ec61-1fcd-407a-a960-712ac715cbf3'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
