# Generated by Django 5.2 on 2025-05-29 14:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('315831fb-2d3e-4ea3-8666-378f66522e2c'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
