# Generated by Django 5.2 on 2025-05-29 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('652f6aff-0ab5-46b7-8b88-072f6ea38800'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
