# Generated by Django 5.2 on 2025-05-29 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userprofile_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('17b676c4-3999-4a12-bab3-cb83455cadcc'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
