# Generated by Django 5.2 on 2025-05-30 13:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_channelsuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelsuser',
            options={'verbose_name': '2. User Channel', 'verbose_name_plural': '2. User Channels'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '1. User', 'verbose_name_plural': '1. Users'},
        ),
        migrations.AlterModelOptions(
            name='referalspoints',
            options={'verbose_name': '3. Referral Points', 'verbose_name_plural': '3. Referral Points'},
        ),
        migrations.AlterField(
            model_name='channelsuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='connecttochannel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connect_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, null=True, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='referals',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referral_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_profile/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('84e750fb-5904-475e-8e98-e3f3cbacfe2e'), editable=False, primary_key=True, serialize=False, verbose_name='UUID'),
        ),
    ]
