# Generated by Django 5.2 on 2025-05-29 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenSwap',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_from', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество от FIPTp')),
                ('amount_to', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Количество до FIPT')),
                ('total_exchange', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Общая сумма обмена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_swaps', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Token Swap',
                'verbose_name_plural': 'Token Swaps',
            },
        ),
    ]
