# Generated by Django 5.2 on 2025-05-29 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_swap', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenswap',
            old_name='amount_from',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='tokenswap',
            name='amount_to',
        ),
        migrations.AlterField(
            model_name='tokenswap',
            name='total_exchange',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Общая сумма обмена FIPT'),
        ),
    ]
