# Generated by Django 5.2 on 2025-05-29 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_swap', '0002_rename_amount_from_tokenswap_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenswap',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Amount from FIPTp'),
        ),
        migrations.AlterField(
            model_name='tokenswap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='tokenswap',
            name='total_exchange',
            field=models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Total FIPT Exchange'),
        ),
        migrations.AlterField(
            model_name='tokenswap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_swaps', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
